/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SaleItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Time = IDL.Int;
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'totalAmount' : IDL.Float64,
  'timestamp' : Time,
  'items' : IDL.Vec(SaleItem),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalSalesAmount' : IDL.Float64,
  'lowStockCount' : IDL.Nat,
  'totalSalesCount' : IDL.Nat,
  'recentSales' : IDL.Vec(Sale),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSale' : IDL.Func([IDL.Vec(SaleItem), IDL.Float64], [IDL.Nat], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsSortedByName' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsSortedByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsSortedByStock' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSaleById' : IDL.Func([IDL.Nat], [Sale], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeProduct' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SaleItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'totalAmount' : IDL.Float64,
    'timestamp' : Time,
    'items' : IDL.Vec(SaleItem),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalSalesAmount' : IDL.Float64,
    'lowStockCount' : IDL.Nat,
    'totalSalesCount' : IDL.Nat,
    'recentSales' : IDL.Vec(Sale),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSale' : IDL.Func([IDL.Vec(SaleItem), IDL.Float64], [IDL.Nat], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsSortedByName' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsSortedByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsSortedByStock' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSaleById' : IDL.Func([IDL.Nat], [Sale], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeProduct' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };